In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "age": [20, 22, np.nan, 25, 22],
    "hours_studied": [2, 5, 3, 8, 5],
    "score": [55, 75, 65, 95, 75],
    "passed": [False, True, True, True, True]
})

In [2]:
df

    age  hours_studied  score  passed
0  20.0              2     55   False
1  22.0              5     75    True
2   NaN              3     65    True
3  25.0              8     95    True
4  22.0              5     75    True

In [6]:
print(df.head())
print(df.shape)
print(df.dtypes)
print(df.describe())

# Select a column
print(df["score"])

# Select rows where the score is at least 70
print(df[df["score"] >= 70])

# Select specific rows and columns
print(df.loc[0:2, ["age", "score"]])

    age  hours_studied  score  passed
0  20.0              2     55   False
1  22.0              5     75    True
2   NaN              3     65    True
3  25.0              8     95    True
4  22.0              5     75    True
(5, 4)
age              float64
hours_studied      int64
score              int64
passed              bool
dtype: object
             age  hours_studied      score
count   4.000000       5.000000   5.000000
mean   22.250000       4.600000  73.000000
std     2.061553       2.302173  14.832397
min    20.000000       2.000000  55.000000
25%    21.500000       3.000000  65.000000
50%    22.000000       5.000000  75.000000
75%    22.750000       5.000000  75.000000
max    25.000000       8.000000  95.000000
0    55
1    75
2    65
3    95
4    75
Name: score, dtype: int64
    age  hours_studied  score  passed
1  22.0              5     75    True
3  25.0              8     95    True
4  22.0              5     75    True
    age  score
0  20.0     55
1  22.0     75
2   NaN     65

In [7]:
# Count missing values per column
print(df.isna().sum())

# Fill missing ages with the median
df["age"] = df["age"].fillna(df["age"].median())

# Remove duplicate records
df = df.drop_duplicates()

print(df.isna().sum())

age              1
hours_studied    0
score            0
passed           0
dtype: int64
age              0
hours_studied    0
score            0
passed           0
dtype: int64

#Fearure engineering

In [8]:
# Create a new feature
df["study_efficiency"] = (
    df["score"] / df["hours_studied"]
)

# Categorize scores
df["performance"] = np.where(
    df["score"] >= 70,
    "Good",
    "Needs improvement"
)

# Summarize the data
print(df.groupby("passed")["score"].mean())

passed
False    55.000000
True     78.333333
Name: score, dtype: float64

/tmp/ipykernel_1481/2283742994.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["study_efficiency"] = (
/tmp/ipykernel_1481/2283742994.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["performance"] = np.where(

In [9]:
df

    age  hours_studied  score  passed  study_efficiency        performance
0  20.0              2     55   False         27.500000  Needs improvement
1  22.0              5     75    True         15.000000               Good
2  22.0              3     65    True         21.666667  Needs improvement
3  25.0              8     95    True         11.875000               Good